name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install ubuntu packages
      run: sudo apt install g++ make python3 python3-pip
    - name: install python packages
      run: pip3 install numpy pandas matplotlib
    - name: make
      run: make
