name: C/C++ build test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install ubuntu packages
      run: sudo apt install g++ make cmake
    - name: cmake
      run: mkdir -p build/; cmake -B build
    - name: make
      run: cd build; sudo make install
