name: LaTeX Build 

on:
  push:
    branches: [ midterm-report ]
  pull_request:
    branches: [ midterm-report ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'midterm-report'
        
    - name: update
      run: sudo apt update
    
    - name: install packages
      run: sudo apt install texlive-full make latexmk biber make python3 python3-pip

    - name: install python packages
      run: pip3 install numpy matplotlib
      
    - name: make latex target
      run: cd midterm_report && make
